# Generated by Django 4.1.7 on 2024-08-30 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0003_snippet_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='title',
        ),
        migrations.AddField(
            model_name='snippet',
            name='lang',
            field=models.CharField(default='Python', max_length=50),
        ),
        migrations.AddField(
            model_name='snippet',
            name='name',
            field=models.CharField(default='Unnamed Snippet', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
